<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFrMjiLu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFrMjiLu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFrMjiLu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFrMjiLu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFrMjiLu\App_KernelDevDebugContainer([
    'container.build_hash' => 'FrMjiLu',
    'container.build_id' => '7bdc077f',
    'container.build_time' => 1624558727,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFrMjiLu');
